image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Flutter
    init: |
      flutter --version
      flutter doctor
    command: echo "Flutter is ready!"

vscode:
  extensions:
    - Dart-Code.flutter

ports:
  - port: 3000
    onOpen: open-preview
